import Link from 'next/link'
import { requireUser } from '@/lib/require-user'
import { updatePurchaseOrder, deletePurchaseOrder, addPurchaseOrderItem, updatePurchaseOrderItem, deletePurchaseOrderItem, receivePurchaseOrderItem } from '@/lib/actions'
import { date, num } from '@/lib/format'

export default async function ShipmentDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const { supabase } = await requireUser()
  const { data: po } = await supabase.from('purchase_orders').select('*, suppliers(name)').eq('id', id).single()
  const { data: suppliers } = await supabase.from('suppliers').select('id, name').order('name')
  const { data: parts } = await supabase.from('parts').select('id, name, sku').order('sku')
  const { data: items } = await supabase.from('purchase_order_items').select('*, parts(name, sku)').eq('purchase_order_id', id).order('created_at')
  const { data: receives } = await supabase.from('receiving_events').select('*, parts(name, sku)').eq('purchase_order_id', id).order('created_at', { ascending: false })

  if (!po) return <div className="card"><h1>Shipment not found</h1><Link className="button" href="/shipments">Back</Link></div>

  return (
    <>
      <div className="page-head"><div><h1>{po.po_number}</h1><p className="muted">Shipment / purchase order detail.</p></div><div className="action-row"><Link className="button secondary" href="/shipments">Back</Link><Link className="button" href="/receiving">Receiving screen</Link></div></div>
      <div className="grid two">
        <div className="card"><h2>Edit shipment</h2><form className="stack" action={updatePurchaseOrder}><input type="hidden" name="id" value={id}/><label>PO number<input name="po_number" defaultValue={po.po_number || ''} required /></label><label>Supplier<select name="supplier_id" defaultValue={po.supplier_id}>{(suppliers || []).map((s:any)=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="form-row"><label>Status<select name="status" defaultValue={po.status}><option value="draft">Draft</option><option value="ordered">Ordered</option><option value="in_production">In production</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="receiving_check">Receiving check</option><option value="partially_received">Partially received</option><option value="received">Received</option><option value="closed">Closed</option><option value="cancelled">Cancelled</option></select></label><label>Order date<input name="order_date" type="date" defaultValue={po.order_date || ''}/></label><label>Expected date<input name="expected_date" type="date" defaultValue={po.expected_date || ''}/></label></div><label>Tracking<input name="tracking_number" defaultValue={po.tracking_number || ''}/></label><label>Notes<textarea name="notes" defaultValue={po.notes || ''}/></label><button type="submit">Save shipment</button></form><form action={deletePurchaseOrder}><input type="hidden" name="id" value={id}/><button className="danger" type="submit">Delete shipment</button></form></div>
        <div className="card"><h2>Add item</h2><form className="stack" action={addPurchaseOrderItem}><input type="hidden" name="purchase_order_id" value={id}/><label>Part<select name="part_id" required><option value="">Choose part</option>{(parts || []).map((p:any)=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><div className="form-row"><label>Qty ordered<input name="quantity_ordered" type="number" step="0.01" required/></label><label>Unit cost<input name="unit_cost" type="number" step="0.01" defaultValue="0"/></label></div><label>Notes<textarea name="notes"/></label><button type="submit">Add item</button></form></div>
      </div>
      <div className="card table-card"><div className="table-head"><h2>Items in shipment</h2></div><div className="wide-table"><table><thead><tr><th>Part</th><th>Ordered</th><th>Received</th><th>Unit cost</th><th>Notes</th><th>Receive now</th><th>Actions</th></tr></thead><tbody>{(items || []).map((i:any) => <tr key={i.id}><td><Link className="link" href={`/parts/${i.part_id}`}>{i.parts?.sku} · {i.parts?.name}</Link></td><td>{num(i.quantity_ordered)}</td><td>{num(i.quantity_received)}</td><td>{num(i.unit_cost)}</td><td>{i.notes}</td><td><form className="stack" action={receivePurchaseOrderItem}><input type="hidden" name="purchase_order_item_id" value={i.id}/><div className="form-row"><label>Good<input name="quantity_received" type="number" step="0.01" defaultValue="0"/></label><label>Damaged<input name="quantity_damaged" type="number" step="0.01" defaultValue="0"/></label><label>Missing<input name="quantity_missing" type="number" step="0.01" defaultValue="0"/></label></div><label>Note<textarea name="notes"/></label><button className="small-btn" type="submit">Receive</button></form></td><td><details><summary className="button small-btn secondary">Edit</summary><form className="stack card flat" action={updatePurchaseOrderItem}><input type="hidden" name="id" value={i.id}/><input type="hidden" name="purchase_order_id" value={id}/><label>Part<select name="part_id" defaultValue={i.part_id}>{(parts || []).map((p:any)=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><label>Qty ordered<input name="quantity_ordered" type="number" step="0.01" defaultValue={i.quantity_ordered}/></label><label>Unit cost<input name="unit_cost" type="number" step="0.01" defaultValue={i.unit_cost}/></label><label>Notes<textarea name="notes" defaultValue={i.notes || ''}/></label><button type="submit">Save</button></form><form action={deletePurchaseOrderItem}><input type="hidden" name="id" value={i.id}/><input type="hidden" name="purchase_order_id" value={id}/><button className="danger small-btn" type="submit">Delete item</button></form></details></td></tr>)}{(items || []).length === 0 && <tr><td colSpan={7}><div className="empty-state">No items added to this shipment.</div></td></tr>}</tbody></table></div></div>
      <div className="card table-card"><div className="table-head"><h2>Receiving history</h2></div><table><thead><tr><th>Date</th><th>Part</th><th>Good</th><th>Damaged</th><th>Missing</th><th>Notes</th></tr></thead><tbody>{(receives || []).map((r:any)=><tr key={r.id}><td>{date(r.created_at)}</td><td>{r.parts?.sku} · {r.parts?.name}</td><td>{num(r.quantity_received)}</td><td>{num(r.quantity_damaged)}</td><td>{num(r.quantity_missing)}</td><td>{r.notes}</td></tr>)}{(receives || []).length === 0 && <tr><td colSpan={6}><div className="empty-state">No receiving events yet.</div></td></tr>}</tbody></table></div>
    </>
  )
}
