-- Seed inventory master data from 2026 New Material and Component Sheet.xlsx
-- This is database seed data, not hardcoded app logic. Records remain editable/archiveable in the app.
-- Safe to rerun: parts/products/variations/BOMs are upserted; seeded starting balances are replaced.

begin;

-- Parts / components
insert into public.parts (name, sku, category, unit, notes, active)
values
  ('6x10 Poly Bubble Mailer', 'PART-6X10-POLY-BUBBLE-MAILER', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('5x10 Yellow Bubble Mailer', 'PART-5X10-YELLOW-BUBBLE-MAILER', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('9x6x2 in Shipping Boxes', 'PART-9X6X2-IN-SHIPPING-BOXES', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('12x9x4 in Shipping Boxes', 'PART-12X9X4-IN-SHIPPING-BOXES', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('5x10 White Bubble Mailer', 'PART-5X10-WHITE-BUBBLE-MAILER', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Clear Acrylic Sheets', 'PART-CLEAR-ACRYLIC-SHEETS', 'Acrylic', 'sheet', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Wood Light Base', 'PART-WOOD-LIGHT-BASE', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('DNL Cracked Light Base', 'PART-DNL-CRACKED-LIGHT-BASE', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('HS Black Light Base', 'PART-HS-BLACK-LIGHT-BASE', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('HS White Light Base', 'PART-HS-WHITE-LIGHT-BASE', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('HS Rippled LIght Base', 'PART-HS-RIPPLED-LIGHT-BASE', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('HS Black Top Part', 'PART-HS-BLACK-TOP-PART', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('HS White Top Part', 'PART-HS-WHITE-TOP-PART', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('9x6x3 in Shipping Boxes', 'PART-9X6X3-IN-SHIPPING-BOXES', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('11x8x2 in Shipping Boxes', 'PART-11X8X2-IN-SHIPPING-BOXES', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('13x11x2 in Shipping Boxes', 'PART-13X11X2-IN-SHIPPING-BOXES', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Foam Pouches', 'PART-FOAM-POUCHES', 'Packaging', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('White Holders', 'PART-WHITE-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('White Tags', 'PART-WHITE-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Burgundy Holders', 'PART-BURGUNDY-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Burgundy Tags', 'PART-BURGUNDY-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Pink Holders', 'PART-PINK-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Pink Tags', 'PART-PINK-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Sage Holders', 'PART-SAGE-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Sage Tags', 'PART-SAGE-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Tan Holders', 'PART-TAN-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Tan Tags', 'PART-TAN-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Navy Holders', 'PART-NAVY-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Navy Tags', 'PART-NAVY-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Gray Holders', 'PART-GRAY-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Gray Tags', 'PART-GRAY-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Black Holders', 'PART-BLACK-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Black Tags', 'PART-BLACK-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Cream Holders', 'PART-CREAM-HOLDERS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Cream Tags', 'PART-CREAM-TAGS', 'Passport Holder Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Navy Blue 1-Slot Watch Case', 'PART-NAVY-BLUE-1-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Navy Blue 2-Slot Watch Case', 'PART-NAVY-BLUE-2-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Navy Blue 3-Slot Watch Case', 'PART-NAVY-BLUE-3-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Brown 1-Slot Watch Case', 'PART-BROWN-1-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Brown 2-Slot Watch Case', 'PART-BROWN-2-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Brown 3-Slot Watch Case', 'PART-BROWN-3-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Black 1-Slot Watch Case', 'PART-BLACK-1-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Black 2-Slot Watch Case', 'PART-BLACK-2-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Black 3-Slot Watch Case', 'PART-BLACK-3-SLOT-WATCH-CASE', 'Watch Case Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Small Birch Recipe Book', 'PART-SMALL-BIRCH-RECIPE-BOOK', 'Recipe Book Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Medium Birch Recipe Book', 'PART-MEDIUM-BIRCH-RECIPE-BOOK', 'Recipe Book Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Large Birch Recipe Book', 'PART-LARGE-BIRCH-RECIPE-BOOK', 'Recipe Book Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Medium Cherry Recipe Book', 'PART-MEDIUM-CHERRY-RECIPE-BOOK', 'Recipe Book Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Large Cherry Recipe Book', 'PART-LARGE-CHERRY-RECIPE-BOOK', 'Recipe Book Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Medium Red Oak Recipe Book', 'PART-MEDIUM-RED-OAK-RECIPE-BOOK', 'Recipe Book Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Large Red Oak Recipe Book', 'PART-LARGE-RED-OAK-RECIPE-BOOK', 'Recipe Book Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Star Map Rectangle Base', 'PART-STAR-MAP-RECTANGLE-BASE', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true),
  ('Star Map U-Shaped Base', 'PART-STAR-MAP-U-SHAPED-BASE', 'Light / Base Components', 'each', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE part columns. Edit/archive in the app as needed.', true)
on conflict (sku) do update set
  name = excluded.name,
  category = excluded.category,
  unit = excluded.unit,
  notes = excluded.notes,
  active = true,
  updated_at = now();

-- Finished product groups
insert into public.products (name, sku, notes, active)
values
  ('Night Lights', 'PROD-NIGHT-LIGHTS', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE finished-product rows. Edit/archive in the app as needed.', true),
  ('Badge Buddies', 'PROD-BADGE-BUDDIES', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE finished-product rows. Edit/archive in the app as needed.', true),
  ('Badge Reels', 'PROD-BADGE-REELS', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE finished-product rows. Edit/archive in the app as needed.', true),
  ('Headphone Stands', 'PROD-HEADPHONE-STANDS', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE finished-product rows. Edit/archive in the app as needed.', true),
  ('Passport Holders', 'PROD-PASSPORT-HOLDERS', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE finished-product rows. Edit/archive in the app as needed.', true),
  ('Watch Cases', 'PROD-WATCH-CASES', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE finished-product rows. Edit/archive in the app as needed.', true),
  ('Recipe Books', 'PROD-RECIPE-BOOKS', 'Seeded from 2026 New Material and Component Sheet - MASTER FILE finished-product rows. Edit/archive in the app as needed.', true)
on conflict (sku) do update set
  name = excluded.name,
  notes = excluded.notes,
  active = true,
  updated_at = now();

-- Finished product variations
insert into public.product_variations (product_id, variation_name, internal_sku, notes, active)
select pr.id, v.variation_name, v.internal_sku, v.notes, true
from (values
  ('PROD-NIGHT-LIGHTS', 'Baby Night Light', 'VAR-BABY-NIGHT-LIGHT', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-NIGHT-LIGHTS', 'Dinasour Night Light', 'VAR-DINASOUR-NIGHT-LIGHT', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-BADGE-BUDDIES', 'Badge Buddy', 'VAR-BADGE-BUDDY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-BADGE-REELS', 'Arcylic Badge Reel', 'VAR-ARCYLIC-BADGE-REEL', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-HEADPHONE-STANDS', 'Headphone Stand', 'VAR-HEADPHONE-STAND', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'White Holder + Tag', 'VAR-WHITE-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'White Holder Only', 'VAR-WHITE-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'White Tag Only', 'VAR-WHITE-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Burgundy Holder + Tag', 'VAR-BURGUNDY-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Burgundy Holder Only', 'VAR-BURGUNDY-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Burgundy Tag Only', 'VAR-BURGUNDY-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Pink Holder + Tag', 'VAR-PINK-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Pink Holder Only', 'VAR-PINK-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Pink Tag Only', 'VAR-PINK-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Sage Holder + Tag', 'VAR-SAGE-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Sage Holder Only', 'VAR-SAGE-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Sage Tag Only', 'VAR-SAGE-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Tan Holder + Tag', 'VAR-TAN-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Tan Holder Only', 'VAR-TAN-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Tan Tag Only', 'VAR-TAN-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Navy Holder + Tag', 'VAR-NAVY-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Navy Holder Only', 'VAR-NAVY-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Navy Tag Only', 'VAR-NAVY-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Gray Holder + Tag', 'VAR-GRAY-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Gray Holder Only', 'VAR-GRAY-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Gray Tag Only', 'VAR-GRAY-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Black Holder + Tag', 'VAR-BLACK-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Black Holder Only', 'VAR-BLACK-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Black Tag Only', 'VAR-BLACK-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Cream Holder + Tag', 'VAR-CREAM-HOLDER-TAG', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Cream Holder Only', 'VAR-CREAM-HOLDER-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-PASSPORT-HOLDERS', 'Cream Tag Only', 'VAR-CREAM-TAG-ONLY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Navy Blue 1-Slot Watch Case', 'VAR-NAVY-BLUE-1-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Navy Blue 2-Slot Watch Case', 'VAR-NAVY-BLUE-2-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Navy Blue 3-Slot Watch Case', 'VAR-NAVY-BLUE-3-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Brown 1-Slot Watch Case', 'VAR-BROWN-1-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Brown 2-Slot Watch Case', 'VAR-BROWN-2-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Brown 3-Slot Watch Case', 'VAR-BROWN-3-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Black 1-Slot Watch Case', 'VAR-BLACK-1-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Black 2-Slot Watch Case', 'VAR-BLACK-2-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-WATCH-CASES', 'Black 3-Slot Watch Case', 'VAR-BLACK-3-SLOT-WATCH-CASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-RECIPE-BOOKS', 'Small Birch Recipe Book', 'VAR-SMALL-BIRCH-RECIPE-BOOK', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-RECIPE-BOOKS', 'Medium Birch Recipe Book', 'VAR-MEDIUM-BIRCH-RECIPE-BOOK', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-RECIPE-BOOKS', 'Large Birch Recipe Book', 'VAR-LARGE-BIRCH-RECIPE-BOOK', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-RECIPE-BOOKS', 'Medium Cherry Recipe Book', 'VAR-MEDIUM-CHERRY-RECIPE-BOOK', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-RECIPE-BOOKS', 'Large Cherry Recipe Book', 'VAR-LARGE-CHERRY-RECIPE-BOOK', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-RECIPE-BOOKS', 'Medium Red Oak Recipe Book', 'VAR-MEDIUM-RED-OAK-RECIPE-BOOK', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-RECIPE-BOOKS', 'Large Red Oak Recipe Book', 'VAR-LARGE-RED-OAK-RECIPE-BOOK', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-NIGHT-LIGHTS', 'Star map Rectangle Base', 'VAR-STAR-MAP-RECTANGLE-BASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-NIGHT-LIGHTS', 'Star map U-Shaped Light base', 'VAR-STAR-MAP-U-SHAPED-LIGHT-BASE', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.'),
  ('PROD-BADGE-BUDDIES', 'TikTok Badge Buddy', 'VAR-TIKTOK-BADGE-BUDDY', 'Seeded from MASTER FILE product/variation row. BOM rows were generated from non-zero component usage.')
) as v(product_sku, variation_name, internal_sku, notes)
join public.products pr on pr.sku = v.product_sku
on conflict (internal_sku) do update set
  product_id = excluded.product_id,
  variation_name = excluded.variation_name,
  notes = excluded.notes,
  active = true,
  updated_at = now();

-- BOM / MASTER FILE component usage
insert into public.bom_items (variation_id, part_id, quantity_per_unit, notes)
select pv.id, p.id, b.quantity_per_unit, 'Seeded from MASTER FILE BOM usage values'
from (values
  ('VAR-BABY-NIGHT-LIGHT', 'PART-6X10-POLY-BUBBLE-MAILER', 0.4814::numeric),
  ('VAR-BABY-NIGHT-LIGHT', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.8075::numeric),
  ('VAR-BABY-NIGHT-LIGHT', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BABY-NIGHT-LIGHT', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.3486::numeric),
  ('VAR-BABY-NIGHT-LIGHT', 'PART-CLEAR-ACRYLIC-SHEETS', 0.172972::numeric),
  ('VAR-BABY-NIGHT-LIGHT', 'PART-WOOD-LIGHT-BASE', 1.02::numeric),
  ('VAR-DINASOUR-NIGHT-LIGHT', 'PART-6X10-POLY-BUBBLE-MAILER', 0.332::numeric),
  ('VAR-DINASOUR-NIGHT-LIGHT', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.8075::numeric),
  ('VAR-DINASOUR-NIGHT-LIGHT', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-DINASOUR-NIGHT-LIGHT', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.498::numeric),
  ('VAR-DINASOUR-NIGHT-LIGHT', 'PART-CLEAR-ACRYLIC-SHEETS', 0.172972::numeric),
  ('VAR-DINASOUR-NIGHT-LIGHT', 'PART-HS-RIPPLED-LIGHT-BASE', 1::numeric),
  ('VAR-BADGE-BUDDY', 'PART-5X10-YELLOW-BUBBLE-MAILER', 0.649::numeric),
  ('VAR-ARCYLIC-BADGE-REEL', 'PART-5X10-YELLOW-BUBBLE-MAILER', 0.4::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.835::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.891::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-CLEAR-ACRYLIC-SHEETS', 0.1379::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-HS-BLACK-LIGHT-BASE', 0.716::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-HS-WHITE-LIGHT-BASE', 0.116::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-HS-RIPPLED-LIGHT-BASE', 0.217::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-HS-BLACK-TOP-PART', 0.716::numeric),
  ('VAR-HEADPHONE-STAND', 'PART-HS-WHITE-TOP-PART', 0.334::numeric),
  ('VAR-WHITE-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-WHITE-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-WHITE-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-WHITE-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-WHITE-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-WHITE-HOLDER-TAG', 'PART-WHITE-HOLDERS', 1.08::numeric),
  ('VAR-WHITE-HOLDER-TAG', 'PART-WHITE-TAGS', 1.08::numeric),
  ('VAR-WHITE-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-WHITE-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-WHITE-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-WHITE-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-WHITE-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-WHITE-HOLDER-ONLY', 'PART-WHITE-HOLDERS', 1.08::numeric),
  ('VAR-WHITE-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-WHITE-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-WHITE-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-WHITE-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-WHITE-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-WHITE-TAG-ONLY', 'PART-WHITE-TAGS', 1.08::numeric),
  ('VAR-BURGUNDY-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-BURGUNDY-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BURGUNDY-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-BURGUNDY-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-BURGUNDY-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-BURGUNDY-HOLDER-TAG', 'PART-BURGUNDY-HOLDERS', 1.08::numeric),
  ('VAR-BURGUNDY-HOLDER-TAG', 'PART-BURGUNDY-TAGS', 1.08::numeric),
  ('VAR-BURGUNDY-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-BURGUNDY-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BURGUNDY-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-BURGUNDY-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-BURGUNDY-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-BURGUNDY-HOLDER-ONLY', 'PART-BURGUNDY-HOLDERS', 1.08::numeric),
  ('VAR-BURGUNDY-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-BURGUNDY-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BURGUNDY-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-BURGUNDY-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-BURGUNDY-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-BURGUNDY-TAG-ONLY', 'PART-BURGUNDY-TAGS', 1.08::numeric),
  ('VAR-PINK-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-PINK-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-PINK-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-PINK-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-PINK-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-PINK-HOLDER-TAG', 'PART-PINK-HOLDERS', 1.08::numeric),
  ('VAR-PINK-HOLDER-TAG', 'PART-PINK-TAGS', 1.08::numeric),
  ('VAR-PINK-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-PINK-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-PINK-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-PINK-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-PINK-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-PINK-HOLDER-ONLY', 'PART-PINK-HOLDERS', 1.08::numeric),
  ('VAR-PINK-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-PINK-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-PINK-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-PINK-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-PINK-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-PINK-TAG-ONLY', 'PART-PINK-TAGS', 1.08::numeric),
  ('VAR-SAGE-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-SAGE-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-SAGE-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-SAGE-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-SAGE-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-SAGE-HOLDER-TAG', 'PART-SAGE-HOLDERS', 1.08::numeric),
  ('VAR-SAGE-HOLDER-TAG', 'PART-SAGE-TAGS', 1.08::numeric),
  ('VAR-SAGE-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-SAGE-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-SAGE-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-SAGE-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-SAGE-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-SAGE-HOLDER-ONLY', 'PART-SAGE-HOLDERS', 1.08::numeric),
  ('VAR-SAGE-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-SAGE-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-SAGE-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-SAGE-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-SAGE-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-SAGE-TAG-ONLY', 'PART-SAGE-TAGS', 1.08::numeric),
  ('VAR-TAN-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-TAN-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-TAN-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-TAN-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-TAN-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-TAN-HOLDER-TAG', 'PART-TAN-HOLDERS', 1.08::numeric),
  ('VAR-TAN-HOLDER-TAG', 'PART-TAN-TAGS', 1.08::numeric),
  ('VAR-TAN-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-TAN-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-TAN-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-TAN-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-TAN-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-TAN-HOLDER-ONLY', 'PART-TAN-HOLDERS', 1.08::numeric),
  ('VAR-TAN-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-TAN-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-TAN-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-TAN-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-TAN-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-TAN-TAG-ONLY', 'PART-TAN-TAGS', 1.08::numeric),
  ('VAR-NAVY-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-NAVY-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-NAVY-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-NAVY-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-NAVY-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-NAVY-HOLDER-TAG', 'PART-NAVY-HOLDERS', 1.08::numeric),
  ('VAR-NAVY-HOLDER-TAG', 'PART-NAVY-TAGS', 1.08::numeric),
  ('VAR-NAVY-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-NAVY-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-NAVY-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-NAVY-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-NAVY-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-NAVY-HOLDER-ONLY', 'PART-NAVY-HOLDERS', 1.08::numeric),
  ('VAR-NAVY-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-NAVY-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-NAVY-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-NAVY-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-NAVY-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-NAVY-TAG-ONLY', 'PART-NAVY-TAGS', 1.08::numeric),
  ('VAR-GRAY-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-GRAY-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-GRAY-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-GRAY-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-GRAY-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-GRAY-HOLDER-TAG', 'PART-GRAY-HOLDERS', 1.08::numeric),
  ('VAR-GRAY-HOLDER-TAG', 'PART-GRAY-TAGS', 1.08::numeric),
  ('VAR-GRAY-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-GRAY-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-GRAY-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-GRAY-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-GRAY-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-GRAY-HOLDER-ONLY', 'PART-GRAY-HOLDERS', 1.08::numeric),
  ('VAR-GRAY-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-GRAY-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-GRAY-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-GRAY-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-GRAY-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-GRAY-TAG-ONLY', 'PART-GRAY-TAGS', 1.08::numeric),
  ('VAR-BLACK-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-BLACK-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BLACK-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-BLACK-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-BLACK-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-BLACK-HOLDER-TAG', 'PART-BLACK-HOLDERS', 1.08::numeric),
  ('VAR-BLACK-HOLDER-TAG', 'PART-BLACK-TAGS', 1.08::numeric),
  ('VAR-BLACK-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-BLACK-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BLACK-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-BLACK-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-BLACK-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-BLACK-HOLDER-ONLY', 'PART-BLACK-HOLDERS', 1.08::numeric),
  ('VAR-BLACK-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-BLACK-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BLACK-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-BLACK-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-BLACK-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-BLACK-TAG-ONLY', 'PART-BLACK-TAGS', 1.08::numeric),
  ('VAR-CREAM-HOLDER-TAG', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-CREAM-HOLDER-TAG', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-CREAM-HOLDER-TAG', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-CREAM-HOLDER-TAG', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-CREAM-HOLDER-TAG', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-CREAM-HOLDER-TAG', 'PART-CREAM-HOLDERS', 1.08::numeric),
  ('VAR-CREAM-HOLDER-TAG', 'PART-CREAM-TAGS', 1.08::numeric),
  ('VAR-CREAM-HOLDER-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-CREAM-HOLDER-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-CREAM-HOLDER-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-CREAM-HOLDER-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-CREAM-HOLDER-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-CREAM-HOLDER-ONLY', 'PART-CREAM-HOLDERS', 1.08::numeric),
  ('VAR-CREAM-TAG-ONLY', 'PART-6X10-POLY-BUBBLE-MAILER', 0.08::numeric),
  ('VAR-CREAM-TAG-ONLY', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-CREAM-TAG-ONLY', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.031::numeric),
  ('VAR-CREAM-TAG-ONLY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.186::numeric),
  ('VAR-CREAM-TAG-ONLY', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.025::numeric),
  ('VAR-CREAM-TAG-ONLY', 'PART-CREAM-TAGS', 1.08::numeric),
  ('VAR-NAVY-BLUE-1-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.009::numeric),
  ('VAR-NAVY-BLUE-1-SLOT-WATCH-CASE', 'PART-9X6X3-IN-SHIPPING-BOXES', 0.642::numeric),
  ('VAR-NAVY-BLUE-1-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-NAVY-BLUE-1-SLOT-WATCH-CASE', 'PART-NAVY-BLUE-1-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-NAVY-BLUE-2-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-NAVY-BLUE-2-SLOT-WATCH-CASE', 'PART-9X6X3-IN-SHIPPING-BOXES', 0.628::numeric),
  ('VAR-NAVY-BLUE-2-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-NAVY-BLUE-2-SLOT-WATCH-CASE', 'PART-NAVY-BLUE-2-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-NAVY-BLUE-3-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.642::numeric),
  ('VAR-NAVY-BLUE-3-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-NAVY-BLUE-3-SLOT-WATCH-CASE', 'PART-NAVY-BLUE-3-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-BROWN-1-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.009::numeric),
  ('VAR-BROWN-1-SLOT-WATCH-CASE', 'PART-9X6X3-IN-SHIPPING-BOXES', 0.642::numeric),
  ('VAR-BROWN-1-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-BROWN-1-SLOT-WATCH-CASE', 'PART-BROWN-1-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-BROWN-2-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BROWN-2-SLOT-WATCH-CASE', 'PART-9X6X3-IN-SHIPPING-BOXES', 0.628::numeric),
  ('VAR-BROWN-2-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-BROWN-2-SLOT-WATCH-CASE', 'PART-BROWN-2-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-BROWN-3-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.642::numeric),
  ('VAR-BROWN-3-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-BROWN-3-SLOT-WATCH-CASE', 'PART-BROWN-3-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-BLACK-1-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.009::numeric),
  ('VAR-BLACK-1-SLOT-WATCH-CASE', 'PART-9X6X3-IN-SHIPPING-BOXES', 0.642::numeric),
  ('VAR-BLACK-1-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-BLACK-1-SLOT-WATCH-CASE', 'PART-BLACK-1-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-BLACK-2-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.023::numeric),
  ('VAR-BLACK-2-SLOT-WATCH-CASE', 'PART-9X6X3-IN-SHIPPING-BOXES', 0.628::numeric),
  ('VAR-BLACK-2-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-BLACK-2-SLOT-WATCH-CASE', 'PART-BLACK-2-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-BLACK-3-SLOT-WATCH-CASE', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.642::numeric),
  ('VAR-BLACK-3-SLOT-WATCH-CASE', 'PART-FOAM-POUCHES', 1::numeric),
  ('VAR-BLACK-3-SLOT-WATCH-CASE', 'PART-BLACK-3-SLOT-WATCH-CASE', 1.11::numeric),
  ('VAR-SMALL-BIRCH-RECIPE-BOOK', 'PART-9X6X2-IN-SHIPPING-BOXES', 0.956::numeric),
  ('VAR-SMALL-BIRCH-RECIPE-BOOK', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.022::numeric),
  ('VAR-SMALL-BIRCH-RECIPE-BOOK', 'PART-SMALL-BIRCH-RECIPE-BOOK', 1.11::numeric),
  ('VAR-MEDIUM-BIRCH-RECIPE-BOOK', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.022::numeric),
  ('VAR-MEDIUM-BIRCH-RECIPE-BOOK', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.956::numeric),
  ('VAR-MEDIUM-BIRCH-RECIPE-BOOK', 'PART-MEDIUM-BIRCH-RECIPE-BOOK', 1.11::numeric),
  ('VAR-LARGE-BIRCH-RECIPE-BOOK', 'PART-13X11X2-IN-SHIPPING-BOXES', 0.956::numeric),
  ('VAR-LARGE-BIRCH-RECIPE-BOOK', 'PART-LARGE-BIRCH-RECIPE-BOOK', 1.67::numeric),
  ('VAR-MEDIUM-CHERRY-RECIPE-BOOK', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.022::numeric),
  ('VAR-MEDIUM-CHERRY-RECIPE-BOOK', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.956::numeric),
  ('VAR-MEDIUM-CHERRY-RECIPE-BOOK', 'PART-MEDIUM-CHERRY-RECIPE-BOOK', 1.82::numeric),
  ('VAR-LARGE-CHERRY-RECIPE-BOOK', 'PART-13X11X2-IN-SHIPPING-BOXES', 0.956::numeric),
  ('VAR-LARGE-CHERRY-RECIPE-BOOK', 'PART-LARGE-CHERRY-RECIPE-BOOK', 2::numeric),
  ('VAR-MEDIUM-RED-OAK-RECIPE-BOOK', 'PART-12X9X4-IN-SHIPPING-BOXES', 0.022::numeric),
  ('VAR-MEDIUM-RED-OAK-RECIPE-BOOK', 'PART-11X8X2-IN-SHIPPING-BOXES', 0.956::numeric),
  ('VAR-MEDIUM-RED-OAK-RECIPE-BOOK', 'PART-MEDIUM-RED-OAK-RECIPE-BOOK', 1.25::numeric),
  ('VAR-LARGE-RED-OAK-RECIPE-BOOK', 'PART-13X11X2-IN-SHIPPING-BOXES', 0.956::numeric),
  ('VAR-LARGE-RED-OAK-RECIPE-BOOK', 'PART-LARGE-RED-OAK-RECIPE-BOOK', 1.25::numeric),
  ('VAR-STAR-MAP-RECTANGLE-BASE', 'PART-6X10-POLY-BUBBLE-MAILER', 1::numeric),
  ('VAR-STAR-MAP-RECTANGLE-BASE', 'PART-11X8X2-IN-SHIPPING-BOXES', 1::numeric),
  ('VAR-STAR-MAP-RECTANGLE-BASE', 'PART-STAR-MAP-RECTANGLE-BASE', 1::numeric),
  ('VAR-STAR-MAP-U-SHAPED-LIGHT-BASE', 'PART-6X10-POLY-BUBBLE-MAILER', 1::numeric),
  ('VAR-STAR-MAP-U-SHAPED-LIGHT-BASE', 'PART-11X8X2-IN-SHIPPING-BOXES', 1::numeric),
  ('VAR-STAR-MAP-U-SHAPED-LIGHT-BASE', 'PART-STAR-MAP-U-SHAPED-BASE', 1::numeric),
  ('VAR-TIKTOK-BADGE-BUDDY', 'PART-5X10-WHITE-BUBBLE-MAILER', 0.86::numeric)
) as b(variation_sku, part_sku, quantity_per_unit)
join public.product_variations pv on pv.internal_sku = b.variation_sku
join public.parts p on p.sku = b.part_sku
on conflict (variation_id, part_id) do update set
  quantity_per_unit = excluded.quantity_per_unit,
  notes = excluded.notes;

-- Starting balances from PREDICTION tab Current Stock row.
delete from public.inventory_movements
where movement_type = 'starting_balance'
  and reason = 'Seeded from 2026 sheet PREDICTION current stock row';

insert into public.inventory_movements (part_id, movement_type, quantity, source_type, reason, notes)
select p.id, 'starting_balance', s.quantity, 'spreadsheet_seed', 'Seeded from 2026 sheet PREDICTION current stock row', 'Starting quantity imported from uploaded spreadsheet. Edit with cycle counts/adjustments if needed.'
from (values
  ('PART-6X10-POLY-BUBBLE-MAILER', 1565.5792::numeric),
  ('PART-5X10-YELLOW-BUBBLE-MAILER', 639.062::numeric),
  ('PART-9X6X2-IN-SHIPPING-BOXES', 2977.1145::numeric),
  ('PART-12X9X4-IN-SHIPPING-BOXES', -41.204::numeric),
  ('PART-5X10-WHITE-BUBBLE-MAILER', 2165.5188::numeric),
  ('PART-CLEAR-ACRYLIC-SHEETS', 312.280292::numeric),
  ('PART-WOOD-LIGHT-BASE', 1256.76::numeric),
  ('PART-HS-BLACK-LIGHT-BASE', 460.36::numeric),
  ('PART-HS-WHITE-LIGHT-BASE', 128.36::numeric),
  ('PART-HS-RIPPLED-LIGHT-BASE', 127.77::numeric),
  ('PART-HS-BLACK-TOP-PART', 419.36::numeric),
  ('PART-HS-WHITE-TOP-PART', 231.54::numeric),
  ('PART-9X6X3-IN-SHIPPING-BOXES', -409.644::numeric),
  ('PART-11X8X2-IN-SHIPPING-BOXES', -231.521::numeric),
  ('PART-13X11X2-IN-SHIPPING-BOXES', -7.372::numeric),
  ('PART-FOAM-POUCHES', -720::numeric),
  ('PART-WHITE-HOLDERS', 70.28::numeric),
  ('PART-WHITE-TAGS', 77::numeric),
  ('PART-BURGUNDY-HOLDERS', 110.2::numeric),
  ('PART-BURGUNDY-TAGS', 116.68::numeric),
  ('PART-PINK-HOLDERS', 122.68::numeric),
  ('PART-PINK-TAGS', 91.92::numeric),
  ('PART-SAGE-HOLDERS', 117.16::numeric),
  ('PART-SAGE-TAGS', 152.16::numeric),
  ('PART-TAN-HOLDERS', 271.88::numeric),
  ('PART-TAN-TAGS', 261.96::numeric),
  ('PART-NAVY-HOLDERS', 344.56::numeric),
  ('PART-NAVY-TAGS', 375.08::numeric),
  ('PART-GRAY-HOLDERS', 127.52::numeric),
  ('PART-GRAY-TAGS', 127.92::numeric),
  ('PART-BLACK-HOLDERS', 303.28::numeric),
  ('PART-BLACK-TAGS', 279.84::numeric),
  ('PART-CREAM-HOLDERS', 285.08::numeric),
  ('PART-CREAM-TAGS', 278.36::numeric),
  ('PART-NAVY-BLUE-1-SLOT-WATCH-CASE', 36.28::numeric),
  ('PART-NAVY-BLUE-2-SLOT-WATCH-CASE', 20.63::numeric),
  ('PART-NAVY-BLUE-3-SLOT-WATCH-CASE', 6.15::numeric),
  ('PART-BROWN-1-SLOT-WATCH-CASE', 100.83::numeric),
  ('PART-BROWN-2-SLOT-WATCH-CASE', 11.36::numeric),
  ('PART-BROWN-3-SLOT-WATCH-CASE', 19.41::numeric),
  ('PART-BLACK-1-SLOT-WATCH-CASE', 48.07::numeric),
  ('PART-BLACK-2-SLOT-WATCH-CASE', 183.71::numeric),
  ('PART-BLACK-3-SLOT-WATCH-CASE', 3.16::numeric),
  ('PART-SMALL-BIRCH-RECIPE-BOOK', 43.23::numeric),
  ('PART-MEDIUM-BIRCH-RECIPE-BOOK', 7.01::numeric),
  ('PART-LARGE-BIRCH-RECIPE-BOOK', 53.31::numeric),
  ('PART-MEDIUM-CHERRY-RECIPE-BOOK', -6.02::numeric),
  ('PART-LARGE-CHERRY-RECIPE-BOOK', 8::numeric),
  ('PART-MEDIUM-RED-OAK-RECIPE-BOOK', 10::numeric),
  ('PART-LARGE-RED-OAK-RECIPE-BOOK', 5.5::numeric),
  ('PART-STAR-MAP-RECTANGLE-BASE', 544::numeric),
  ('PART-STAR-MAP-U-SHAPED-BASE', 567::numeric)
) as s(part_sku, quantity)
join public.parts p on p.sku = s.part_sku;

commit;